[build]
  command = "git submodule update --init --recursive && cd www/src/blog && git pull origin main && cd ../../.. && npm install && npx eleventy"
  publish = "public"

[build.environment]
  NODE_VERSION = "20"

[build.processing]
  git_submodules = true
