[build]
  command = "git submodule update --remote && npm install && npx eleventy"
  publish = "public"

[build.environment]
  NODE_VERSION = "20"
  GIT_SSH_COMMAND = "ssh -o StrictHostKeyChecking=no"

[build.processing]
  git_submodules = true
